---
author: "Alexander Gibson"
categories:
date: "2024-10-30"
draft: false
excerpt: I tracked my caffeine consumption over the course of three months while completing my first PhD assessment. Here's how much I had.
layout: single
subtitle: As a coffee and numbers lover I've always wondered how much I have. So I set to find out.
title: I took 9565mg of caffeine
auto_ids: false
---
At the end of my MPhil I had completed a great deal of work. But I was left wondering some stats... How many hours did I put into this? How many words did I write? How many words did I read? Or, how much caffeine did I consume?

Given I was continuing with a PhD I thought it will be easy enough to track my coffee consumption. And that's exactly what I've been doing for the last three months.

I started my PhD on the 31st of July 2024 and began data collection the same day. I collected data for the number of times I had a:
- Nespresso pod coffee
- Medium coffee
- Large coffee
- Medium iced coffee
- Large iced coffee
- Energy Drink

The Nespresso pods were my morning coffee at home. I noted medium and large were to estimate differences in caffeine content while hot or iced I noted out of interest (with enough data to examine seasonal differences!). Energy drinks are self explanatory. 

**So whats the count up to?**

Well my first PhD assessment was completed on the 31st of October, exactly 3 months after starting and this is where I begin to examine the data.

In total I had 120 coffees and 4 energy drinks! Or a mean average of 1.33 drinks a day.

Now if we assume that the Nespresso pods have 75mg of caffeine, a medium coffee at 60mg, a large coffee at 80mg and the energy drinks (monsters) at 160mg. Then as a total I had 95 nespresso pods, 9 medium coffees, 10 large coffees, 1 medium iced coffee, 5 large iced coffees and 4 energy drinks. 

A little bit of math later and that works out to 9,565mg of caffeine! Nearly 10 grams of caffeine in the time to get my first assessment done.

But why have I tracked this? Well, because I can! There aren't many reasons other than personal interest. But this is only the start, I still have 2 years and 9 months of caffeine data to collect. I'm particularly interested to see if my consumption changes around assessments, intense writing periods or even if it changes with the seasons. But that's for another day.

Welcome to my curiosity chronicles!







