---
author: "Alexander Gibson"
categories:
date: "2026-05-06"
draft: true
excerpt: What you do as researchers and clinician’s matters, and it matters to the patients. When planning your next study, it’s worth the time to reflect on the motivation and justification. 
layout: single
subtitle:
title: For the patient or the paper?
auto_ids: false
---
The other day I was interviewed by a journalist regarding my recent work in identifying [unreliable data used in medical research](https://doi.org/10.64898/2026.02.24.26347028). During our discussion I made the comment “is the work for the patients or the paper?” and it hasn’t left my mind.

Since the first year of my undergraduate in Biomedical Science, it was instilled in us there is a patient – a parent, a sibling or friend – at the end of our work. Regardless if we have direct contact or feedback with them, our actions likely in some way will influence their care or treatment. Yet, as the publish or perish culture persists, I am still concerned more weight is placed on paper metrics than real change. Publish or perish being the incentives to gain funding or employment by increasing quantity over quality of work to reach performance metrics.

Though, the aim of applied medical research is to better the health and wellbeing of individuals through advancements in technology, practice, evidence and policy. When this aim shifts to publishing papers, it no longer serves its purpose. What you do as researchers and clinician’s matters, and it matters to patients. When planning your next study, it’s worth the time to reflect deeply on the motivation, justification and output.

More than 60 years ago, the Declaration of Helsinki set the ethical principles for medical research involving human participants. Early last year I found a typo in the latest updated Declaration which was promptly corrected by the World Medical Association. My best assumption is the error was up for six months before I found it. But I was left wondering, if there for six months, were researchers and clinicians were even reading these global principles that need be upheld.

One of these principles being:

- “The primary purpose of medical research involving human participants is to generate knowledge to understand the causes, development and effects of diseases; improve preventive, diagnostic and therapeutic interventions; and **ultimately to advance individual and public health**.” [WMA](https://www.wma.net/policies-post/wma-declaration-of-helsinki/)

Thankfully, institutions like the Queensland University of Technology (QUT) are moving towards including quality and impact based assessments. QUT having signed the Declaration on Research Assessment [(DORA)](https://sfdora.org/), is [publicly committed](https://share.google/Xlo9CmzdSoukmL3Cs) to improving the evaluation of researchers and their outputs. Changing the way we frame the importance of our research matters, and a top down approach will fast track values in quality. Shifting from quantity to quality will help serve the interests of individual and public health.

Additionally, Australia’s National Health and Medical Research Council fully supports DORA and are [signatories of the Coalition for Advancing Research Assessment](https://www.nhmrc.gov.au/about-us/publications/nhmrc-action-plan-responsible-research-assessment). However, even as Australia and one of its leading funding bodies is actively moving towards quality assessment, your Australian institution likely isn’t. Twenty-eight Australian organisations have signed DORA, while only [three of these are universities](https://sfdora.org/signers/?_organization_country=australia&_signer_type=organisation). 

If you are an Australian researcher, this might be a moment to reflect in your team, how the importance of your research is measured and assessed. **Will your work be for the patients, or the paper?** Perhaps you should know if your university is one of the three that publicly values quality through DORA, or if not, why?




